name: daily-news
on:
  schedule:
    - cron: '0 22 * * *' # 한국 시간 오전 7시 실행
  workflow_dispatch: # 수동 실행 버튼 생성
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # v3를 v4로 변경 (최신 버전 부품)
      - uses: actions/checkout@v4 
      
      # v4를 v5로 변경 (최신 버전 부품)
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.9'
          
      - run: pip install requests beautifulsoup4
      
      - name: Run
        env:
          NAVER_USER_ID: ${{ secrets.NAVER_USER_ID }}
          NAVER_USER_PW: ${{ secrets.NAVER_USER_PW }}
        run: python news_script.py
